### PR TITLE
update arxiv submission to latest version April 2019

### PR DESCRIPTION
**Pull request by biphasic**

### CODE REVIEW

**Comment by guillermogb** [comment]
I think this change is not needed. Even if you keep updating the file on arxiv, it is first stamped on 2018 (as the arxiv id reveals, arXiv:18xx ). Unless we change it from arXiv to a peer-reviewed publication venue in 2019. Is this the case?

**Comment by biphasic** [comment]
Not the case. Thought it would be nice to refer to the last version as that's what the video shows. Your call.

**Comment by guillermogb** [comment]
Oh, I see, you changed the title.
Can we just replace the title in the current entry, until the peer-reviewed version?

**Comment by biphasic** [comment]
Changed the title!

**Comment by guillermogb** [comment]
thanks!

**Pull request merged**
